spring:
  application:
    name: 'auth-gateway'
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:10000/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://localhost:10000/auth/realms/master/protocol/openid-connect/auth
            userinfo-uri: http://localhost:10000/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-with-test-scope:
            provider: keycloak
            client-id: spring-with-test-scope
            client-secret: 7c8400ef-8d57-4dfb-875a-be36a7007f34
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
          keycloak-without-test-scope:
            provider: keycloak
            client-id: spring-without-test-scope
            client-secret: c5077547-feed-4388-8265-307c361f30f2
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  spring:
    application:
      name: gateway
    cloud:
      gateway:
        default-filters:
          - TokenRelay
        routes:
          - id: auth-server
            uri: http://127.0.0.1:4968
            predicates:
              - Path=/callme/**
            filters:
              - RemoveRequestHeader=Cookie
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 3865
