server:
  port: 5555
spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: loja
          uri: lb://loja
          predicates:
            - Path=/loja/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
