server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/herikLorencao/microservices-profiles
          search-paths: fornecedor
          default-label: main
